module.exports = [
  {
    date: 'April 1',
    source: 'Income',
    amount: 1000,
    from: 'N/A',
    category: 'N/A',
  },
  {
    date: 'April 1',
    source: 'Taxes',
    amount: -300,
    from: 'N/A',
    category: 'N/A',
  },
  {
    date: 'April 1',
    source: 'Retirement',
    amount: -200,
    from: 'N/A',
    category: 'N/A',
  },
  {
    date: 'April 1',
    source: 'Savings',
    amount: -100,
    from: 'N/A',
    category: 'N/A',
  },
  {
    date: 'April 1',
    source: 'Credit Card Payment',
    amount: -100,
    from: 'N/A',
    category: 'N/A',
  },
  {
    date: 'April 5',
    source: 'Monthly Birthday Money from Aunt Tilda',
    amount: 20,
    from: 'N/A',
    category: 'N/A',
  },
  {
    date: 'April 5',
    source: 'Coffee',
    amount: -4,
    from: 'N/A',
    category: 'N/A',
  },
  {
    date: 'April 5',
    source: 'Internet',
    amount: -100,
    from: 'N/A',
    category: 'N/A',
  },
  {
    date: 'April 3',
    source: 'Groceries',
    amount: -76,
    from: 'N/A',
    category: 'N/A',
  },
  {
    date: 'April 3',
    source: 'Pet Food',
    amount: -7,
    from: 'N/A',
    category: 'N/A',
  },
];
